// TODO: Insert departments into DB with kewordized id as id, only insert if not exist
export const departmentTitles = [
  'Admissions',
  'Anesthetics',
  'Breast Screening',
  'Burn Center',
  'Cardiology',
  'Central Sterile Services Department',
  'Chaplaincy',
  'Coronary Care Unit',
  'Critical Care',
  'Diagnostic Imaging',
  'Discharge Lounge',
  'Elderly services',
  'Finance Department',
  'Gastroenterology',
  'General Services',
  'General Surgery',
  'Gynecology',
  'Haematology',
  'Health & Safety',
  'Intensive Care Unit',
  'Human Resources',
  'Infection Control',
  'Information Management',
  'Maternity',
  'Medical Records',
  'Microbiology',
  'Neonatal',
  'Nephrology',
  'Neurology',
  'Nutrition and Dietetics',
  'Obstetrics/Gynecology',
  'Occupational Therapy',
  'Oncology',
  'Ophthalmology',
  'Orthopaedics',
  'Otolaryngology',
  'Pain Management',
  'Patient Accounts',
  'Patient Services',
  'Pharmacy',
  'Physiotherapy',
  'Purchasing & Supplies',
  'Radiology',
  'Radiotherapy',
  'Renal',
  'Rheumatology',
  'Sexual Health',
  'Social Work',
  'Urology',
];
