version: '3'

services:
  crux:
    build: server
    volumes:
      - ./server/db:/usr/lib/crux/db
      - ./server/event-log:/usr/lib/crux/event-log
    ports:
      # Crux
      - 3000:3000
      # JMX
      - 9010:9010
      # Prometheus metrics
      - 8080:8080

  prom:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
